# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        food:
            uri_prefix: /images/food
            upload_destination: '%kernel.project_dir%/public/images/food'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
